#pragma once

#include <iostream>
#include <thread>

#include "candidate.h"
#include "compare.h"
#include "ed25519_keys_generator.h"

namespace yggdrasil_cpp_genkeys
{

/**
 * @brief Worker class for generating and evaluating Ed25519 cryptographic keys.
 * 
 * This class runs in a separate thread and continuously generates key pairs,
 * comparing them against local and global best candidates. It supports
 * thread-safe synchronization of best keys between workers.
 */
class Worker
{
   public:
    /**
     * @brief Constructs a Worker and initializes key generators and best key records.
     * 
     * Initializes the Ed25519 key generator, generates an initial key pair,
     * sets up initial best key values, and initializes the global best key
     * with a sentinel value (0xFF in first byte).
     */
    Worker(const Settings& settings, size_t num)
        : settings_(settings), num_(num)
    {
        // Generate initial random key pair
        generator_.Generate(true);

        best_.keys = generator_.Keys();
        best_.zero_bits = LeadingZeroBits(best_.keys.public_key);
        local_best_ = best_;
    }

    /**
     * @brief Main processing loop that generates and evaluates keys continuously.
     * 
     * This method runs in a worker thread until a stop request is received.
     * It generates Ed25519 key pairs and evaluates them against current best keys.
     * Synchronizes with global best keys every 1000 generations.
     * 
     * @param stoken Stop token for cooperative thread interruption.
     */
    void Process(
        std::stop_token stoken)  // NOLINT(performance-unnecessary-value-param)
    {
        constexpr uint64_t SYNC_PERIOD = 1000;
        while (!stoken.stop_requested()) {
            ++generated_keys_count_;

            if ((generated_keys_count_ % SYNC_PERIOD) == 0) {
                Sync();
            }

            generator_.Generate();
            Candidate candidate;
            candidate.keys = generator_.Keys();
            candidate.zero_bits = LeadingZeroBits(candidate.keys.public_key);
            if (settings_.ipv6_nice) {
                candidate.addr = AddrForKey(candidate.keys.public_key);
                candidate.ipv6_zero_blocks = AddressZeroBlocks(candidate.addr);
            }

            if (candidate.IsBetter(best_, settings_.ipv6_nice)) {
                NewBest(candidate);
            }
        }
    }

    /**
     * @brief Retrieves the current local best keys (thread-safe).
     * 
     * @return reference to the current local best keys.
     */
    Candidate GetBest() const
    {
        const std::lock_guard locker(mtx_);
        Candidate result;
        const volatile Candidate* src = &local_best_;
        // NOLINTNEXTLINE(cppcoreguidelines-pro-type-const-cast)
        std::memcpy(&result, const_cast<const Candidate*>(src),
                    sizeof(Candidate));
        std::atomic_signal_fence(std::memory_order_seq_cst);
        return result;
    }

    /**
     * @brief Gets the total number of keys generated by this worker.
     * 
     * @return Count of generated keys (atomically updated every 1000 generations).
     */
    uint64_t GetGeneratedKeysCount() const
    {
        return local_generated_keys_count_;
    }

   private:
    Settings settings_;
    size_t num_ = 0;
    Ed25519_KeysGenerator generator_;  ///< key pair generator
    Candidate best_;                   ///< best candidate found by this worker
    mutable std::mutex mtx_;           ///< mutex for thread-safety
    Candidate local_best_;             ///< best found by this worker
    uint64_t generated_keys_count_ = 0;  ///< counter of generated keys
    std::atomic<uint64_t> local_generated_keys_count_ = 0;
    ///< thread-safe counter for external access

    /**
     * @brief Synchronizes local with global
     * 
     * Updates the thread-safe generation counter.
     * Called periodically (every 1000 generations).
     */
    void Sync() { local_generated_keys_count_ = generated_keys_count_; }

    /**
     * @brief Updates local best records when a new better key is found.
     * 
     * Updates the best public key and stores the complete key pair in local_best_keys_.
     * This method assumes the new key has already been validated as "better".
     */
    void NewBest(const Candidate& candidate)
    {
        best_ = candidate;
        best_.addr = AddrForKey(best_.keys.public_key);
        best_.zero_bits = LeadingZeroBits(best_.keys.public_key);
        if (settings_.verbose) {
            std::println("    thread {:3}: new best z={:2} | pub={} | ip={}",
                         num_, best_.zero_bits, best_.keys.public_key.ToHex(),
                         best_.addr.ToString());
        }
        const std::lock_guard locker(mtx_);
        local_best_ = best_;
    }
};

}  // namespace yggdrasil_cpp_genkeys